import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin} from 'react-icons/ai';
import Image from "next/image";
import deved from '../public/fabio-wave.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>FabianNavarroPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>DevelopedByFabian</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10"> 
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Fabian Navarro</h2>
            <h3 className='Text-2xl py-2'>Professional Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, dicta aperiam? Maxime corrupti possimus nihil tempore repudiandae, suscipit laborum excepturi. Est vitae provident voluptas numquam modi maxime natus explicabo repellat. 
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillLinkedin />
            <AiFillTwitterCircle />
          </div>
          <div className= "relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved}/>
          </div>
        </section>
        
        <section>
          <div>
            <h3 classname="text-3xl py-1">Services I offer:</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint accusamus, saepe architecto repudiandae, ut repellendus quis dolorem minima, magni at quidem. Dicta necessitatibus ad corporis veritatis deserunt cupiditate voluptates pariatur?</p>

          </div>
        </section>

      </main>
    </div>
  )
}


//31:49